all:
	$(info use `make loop` or `make buggy`.)

loop: loop.c
	$(error No commands added yet to build $@ !)

buggy: buggy.c
	$(error No commands added yet to build $@ !)

.PHONY: clean
clean:
	rm -fv loop buggy
	rm -fv *~ #*#
